apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/instance: order
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: order
    app.kubernetes.io/instance: order

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/instance: payment
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: payment
    app.kubernetes.io/instance: payment
---
apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/instance: notification
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8004
      targetPort: 8004
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: notification
    app.kubernetes.io/instance: notification
  
